version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "canal_service"
      POSTGRES_USER: "canal_service"
      POSTGRES_PASSWORD: "canal_service"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U canal_service"]
      interval: 5s
      timeout: 5s
      retries: 5
  purchase_monitoring:
    depends_on:
      db:
        condition: service_healthy
    build: purchase_monitoring
  api:
    depends_on:
      db:
        condition: service_healthy
    build: api
    ports:
      - "5000:5000"
